spring:
  redis:
    port: 49154
    host: localhost
    username: default
    password: redispw
  flyway:
    enabled: true
    encoding: UTF-8
    clean-disabled: true
    locations: classpath:db/migration
    # sql文件命名规范：V版本号__描述.sql，例：V1.0__init_db.sql
    sql-migration-prefix: V  # V代表版本迁移，U代表撤销迁移，R代表可重复迁移
    sql-migration-separator: __   # 分隔符：固定由两个下划线 __ 组成
    sql-migration-suffixes: .sql  # 后缀
    validate-on-migrate: true     # 执行迁移时是否自动调用验证
    baseline-on-migrate: true     # 迁